# Generated by Django 3.1.3 on 2020-11-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='seller',
            field=models.CharField(max_length=110),
        ),
    ]
